services:
    web_shop.security.login_form_authenticator:
        class: WebShopBundle\Security\LoginFormAuthenticator
        autowire: true

    web_shop.security.encoder:
            class: WebShopBundle\Security\Encoder
            autowire: true

    web_shop.doctrine.hash_password_listener:
        class: WebShopBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    web_shop.service.order_service:
        class: WebShopBundle\Service\OrderService
        autowire: true

    web_shop.service.promotions_service:
        class: WebShopBundle\Service\PromotionsService
        autowire: true

    # Twig
    web_shop.twig.web_shop_extension:
        class: WebShopBundle\Twig\WebShopExtension
        calls:
            - [initRuntime, ['@twig']]
        tags:
            - { name: twig.extension }

    web_shop.service.cart_service:
        class: WebShopBundle\Service\CartService
        autowire: true